export const companiesFilters = [
  {
    label: "Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "approved", label: "Approved" },
      { id: "pending-approval", label: "Pending Approval" },
      { id: "rejected", label: "Rejected" },
      { id: "closed", label: "Closed" },
    ],
  },
  {
    label: "Posted Date",
    componentType: "calendar",
    placeholder: "Select Date",
    name: "postedDate",
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "Company",
    componentType: "multi-select",
    placeholder: "Select Companies",
    name: "company",
    options: [
      { id: "techcorp", label: "TechCorp Solutions" },
      { id: "healthcare", label: "Healthcare Plus" },
      { id: "edutech", label: "EduTech Innovations" },
      { id: "fintech", label: "FinTech Services" },
      { id: "retail", label: "Retail Giants" },
      { id: "manufacturing", label: "Manufacturing Pro" },
      { id: "consulting", label: "Consulting Experts" },
      { id: "startup", label: "StartUp Hub" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "finance", label: "Finance" },
      { id: "retail", label: "Retail" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "consulting", label: "Consulting" },
      { id: "telecommunications", label: "Telecommunications" },
      { id: "automotive", label: "Automotive" },
      { id: "real-estate", label: "Real Estate" },
      { id: "media", label: "Media & Entertainment" },
      { id: "logistics", label: "Logistics & Transportation" },
    ],
  },
];

// Mock data - Replace with actual API call
export const companies = [
  {
    id: "1001",
    name: "TechCorp Solutions",
    industry: "Technology",
    contact: "admin@techcorp.com",
    jobs: 25,
    location: "Mumbai, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
  {
    id: "1002",
    name: "Healthcare Plus",
    industry: "Healthcare",
    contact: "hr@healthcareplus.com",
    jobs: 12,
    location: "Delhi, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
  {
    id: "1003",
    name: "EduTech Innovations",
    industry: "Education",
    contact: "contact@edutech.com",
    jobs: 5,
    location: "Bangalore, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
  {
    id: "1004",
    name: "FinTech Services",
    industry: "Finance",
    contact: "info@fintech.com",
    jobs: 18,
    location: "Chennai, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
  {
    id: "1005",
    name: "Retail Giants",
    industry: "Retail",
    contact: "careers@retailgiants.com",
    jobs: 8,
    location: "Hyderabad, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
  {
    id: "1006",
    name: "Manufacturing Pro",
    industry: "Manufacturing",
    contact: "hr@manufacturingpro.com",
    jobs: 15,
    location: "Pune, India",
    description:
      "Stimuler has helped over 3.5 Million people improve their conversational skills using its Audio AI technology. Our AI engines listen, provide detailed feedback on essential speech metrics, and offer guided practice for improvement. Awarded Google Play’s Best AI App and backed by some of the world’s best VC funds, our app has impacted users from over 200 countries till date.",
    totalApplicants: 128,
    acceptedApplicants: 76,
    rejectedApplicants: 32,
    pendingApplicants: 20,
    logo: "/google.png",
  },
];
