export const recruitersFilters = [
  {
    label: "Job Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "jobStatus",
    options: [
      { id: "active", label: "Active" },
      { id: "posted", label: "Posted" },
      { id: "closed", label: "Closed" },
      { id: "draft", label: "Draft" },
      { id: "on-hold", label: "On Hold" },
    ],
  },
  {
    label: "Posted Date",
    componentType: "calendar",
    placeholder: "Select Date",
    name: "postedDate",
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
      { id: "noida", label: "Noida" },
      { id: "gurgaon", label: "Gurgaon" },
    ],
  },
  {
    label: "Company",
    componentType: "multi-select",
    placeholder: "Select Companies",
    name: "company",
    options: [
      { id: "tech-corp", label: "Tech Corp" },
      { id: "innovate-solutions", label: "Innovate Solutions" },
      { id: "global-systems", label: "Global Systems" },
      { id: "digital-dynamics", label: "Digital Dynamics" },
      { id: "future-tech", label: "Future Tech" },
      { id: "smart-ventures", label: "Smart Ventures" },
      { id: "nexgen-solutions", label: "NextGen Solutions" },
      { id: "apex-innovations", label: "Apex Innovations" },
      { id: "quantum-systems", label: "Quantum Systems" },
      { id: "synergy-corp", label: "Synergy Corp" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "retail", label: "Retail" },
      { id: "e-commerce", label: "E-commerce" },
      { id: "consulting", label: "Consulting" },
      { id: "media", label: "Media & Entertainment" },
      { id: "real-estate", label: "Real Estate" },
      { id: "telecommunications", label: "Telecommunications" },
      { id: "automotive", label: "Automotive" },
    ],
  },
];
